LANGUAGES = ["English", "Azerbaijani", "Turkish", "Russian"]

_lang = "English"

_L = {
    "English": {
        "title": "◈  LUMTEXT",
        "section_selected": "SELECTED TEXT",
        "section_action": "ACTION",
        "no_text_warning": "⚠ No text selected — select text first",
        "action_format": "Fix & simplify sentence",
        "action_translate": "Translate",
        "action_email": "Adapt for email",
        "action_summarize": "Summarize",
        "action_tone_formal": "Convert to formal tone",
        "action_tone_casual": "Convert to casual tone",
        "action_bulletpoints": "Convert to bullet points",
        "translate_lang_label": "Language:",
        "result_placeholder": "Result will appear here…",
        "status_api_missing": "⚠ API key not found — Check settings",
        "status_processing": "AI is responding…",
        "status_ready": "✓ Ready",
        "status_error": "✗ Error: {error}",
        "btn_run": "▶  Run",
        "btn_rerun": "▶  Run again",
        "btn_cancel": "Close",
        "btn_copy_fmt": "⎘ Copy (formatted)",
        "btn_copy_plain": "⎘ Copy plain",
        "btn_replace": "↩ Replace",
        "btn_actions": "☰ Actions",
        "btn_actions_hide": "▾ Hide actions",
        "btn_waiting": "⏳ Waiting…",
        "copy_success_fmt": "✓ Formatted copied!",
        "copy_success_plain": "✓ Copied!",
        "replace_tooltip": "Replace selected text with result",
        "fetch_tooltip": "Refresh OpenRouter models",
        "fetch_status_no_key": "⚠ OpenRouter API key missing — Check settings",
        "fetch_status_error": "✗ Fetch error: {error}",
        "provider_no_key": "{p}  (❌ no key)",
        "tray_tooltip": "Lumtext — Select text, press Ctrl+Shift+Space",
        "tray_open_settings": "◈  Open Settings",
        "tray_hotkey_info": "⌨  Select text → Ctrl+Shift+Space",
        "tray_quit": "✕  Quit",
        "startup_message": "Program is running!\n1. Select text\n2. Press Ctrl+Shift+Space\n\n"
                          "If shortcut doesn't work: Settings → Set shortcut guide",
        "tray_tooltip_fmt": "Lumtext\nShortcut: {hotkey}",
        "settings_title": "Lumtext — Settings",
        "settings_subtitle": "Settings · Configuration",
        "btn_save": "✓  Save",
        "tab_model": "  ⚙  Model & API  ",
        "tab_hotkey": "  ⌨  Shortcuts  ",
        "tab_languages": "  🌐  Languages  ",
        "section_provider": "AI PROVIDER",
        "label_provider": "Provider:",
        "label_model": "Model:",
        "btn_fetch_models": "⟳ Load models",
        "or_hint": "💡 You can type any model ID from openrouter.ai/models",
        "section_api_keys": "API KEYS",
        "api_key_placeholder": "Enter {p} API key…",
        "section_hotkey": "GLOBAL SHORTCUT",
        "label_current_hotkey": "Current shortcut:",
        "label_new_hotkey": "New shortcut:",
        "hotkey_placeholder": "e.g., <ctrl>+<shift>+a",
        "btn_set_hotkey": "Set",
        "hotkey_format_hint": "Format: <ctrl>+<shift>+a  ·  <ctrl>+<alt>+t  ·  <super>+h",
        "section_system_hotkeys": "OCCUPIED SYSTEM SHORTCUTS",
        "hotkey_note": "The following shortcuts are already in use — avoid them:",
        "btn_refresh_hotkeys": "⟳  Refresh list",
        "section_translate_langs": "TRANSLATION LANGUAGES",
        "lang_note": "Languages shown in the popup list (max 6):",
        "section_ui_lang": "UI LANGUAGE",
        "label_ui_lang": "Interface language:",
        "dialog_error": "Error",
        "dialog_hotkey_empty": "Shortcut cannot be empty",
        "dialog_invalid_format": "Invalid format",
        "dialog_warning": "Warning",
        "dialog_max_langs": "You can select at most 6 languages",
        "dialog_saved": "Saved",
        "dialog_saved_msg": "✓ All settings saved!",
        "dialog_no_key_title": "No API Key",
        "dialog_no_key_msg": "Enter OpenRouter API key first",
        "or_fetching": "⏳ Loading…",
        "or_loaded": "✓ {count} models",
        "or_fetch_error_title": "Load Error",
        "or_fetch_error_msg": "Could not load OpenRouter models:\n{error}",
    },
    "Azerbaijani": {
        "title": "◈  LUMTEXT",
        "section_selected": "SEÇİLMİŞ MƏTİN",
        "section_action": "ƏMƏLİYYAT",
        "no_text_warning": "⚠ Mətn seçilməyib — əvvəlcə mətni seçin",
        "action_format": "Cümləni düzəlt & sadələşdir",
        "action_translate": "Tərcümə et",
        "action_email": "Email üçün uyğunlaşdır",
        "action_summarize": "Xülasə et",
        "action_tone_formal": "Rəsmi (formal) üsluba çevir",
        "action_tone_casual": "Gündəlik (informal) üsluba çevir",
        "action_bulletpoints": "Bullet point siyahısına çevir",
        "translate_lang_label": "Dil:",
        "result_placeholder": "Nəticə burada görünəcək…",
        "status_api_missing": "⚠ API açarı tapılmadı — Ayarları yoxlayın",
        "status_processing": "AI cavab verir…",
        "status_ready": "✓ Hazırdır",
        "status_error": "✗ Xəta: {error}",
        "btn_run": "▶  İcra et",
        "btn_rerun": "▶  Yenidən icra et",
        "btn_cancel": "Bağla",
        "btn_copy_fmt": "⎘ Kopyala (formatlı)",
        "btn_copy_plain": "⎘ Düz kopyala",
        "btn_replace": "↩ Əvəz et",
        "btn_actions": "☰ Əməliyyatlar",
        "btn_actions_hide": "▾ Əməliyyatları gizlə",
        "btn_waiting": "⏳ Gözləyin…",
        "copy_success_fmt": "✓ Formatlı kopyalandı!",
        "copy_success_plain": "✓ Kopyalandı!",
        "replace_tooltip": "Seçilmiş mətni nəticə ilə əvəz edər",
        "fetch_tooltip": "OpenRouter modellərini yenilə",
        "fetch_status_no_key": "⚠ OpenRouter API açarı yoxdur — Ayarları yoxlayın",
        "fetch_status_error": "✗ Yükləmə xətası: {error}",
        "provider_no_key": "{p}  (❌ açar yoxdur)",
        "tray_tooltip": "Lumtext — Mətni seç, Ctrl+Shift+Space bas",
        "tray_open_settings": "◈  Ayarları Aç",
        "tray_hotkey_info": "⌨  Mətni seç → Ctrl+Shift+Space",
        "tray_quit": "✕  Çıx",
        "startup_message": "Proqram işləyir!\n1. Mətni seçin\n2. Ctrl+Shift+Space basın\n\n"
                          "Qısayol işləmirsə: Ayarlar → Qısayol təyin etmə təlimatı",
        "tray_tooltip_fmt": "Lumtext\nQısayol: {hotkey}",
        "settings_title": "Lumtext — Ayarlar",
        "settings_subtitle": "AYARLAR · KONFIQURASIYA",
        "btn_save": "✓  Yadda saxla",
        "tab_model": "  ⚙  Model & API  ",
        "tab_hotkey": "  ⌨  Qısayollar  ",
        "tab_languages": "  🌐  Dillər  ",
        "section_provider": "AI PROVAYDERİ",
        "label_provider": "Provayder:",
        "label_model": "Model:",
        "btn_fetch_models": "⟳ Modelləri yüklə",
        "or_hint": "💡 openrouter.ai/models səhifəsindən istənilən model ID-sini yuxarıya yaza bilərsiniz",
        "section_api_keys": "API AÇARLARI",
        "api_key_placeholder": "{p} API açarını daxil edin…",
        "section_hotkey": "GLOBAL QISAYOL",
        "label_current_hotkey": "Mövcud qısayol:",
        "label_new_hotkey": "Yeni qısayol:",
        "hotkey_placeholder": "məs: <ctrl>+<shift>+a",
        "btn_set_hotkey": "Təyin et",
        "hotkey_format_hint": "Format: <ctrl>+<shift>+a  ·  <ctrl>+<alt>+t  ·  <super>+h",
        "section_system_hotkeys": "SİSTEMDƏ MƏŞĞUL OLAN QISAYOLLAR",
        "hotkey_note": "Aşağıdakı qısayollar artıq sistemdə istifadə olunur — bunları seçməyin:",
        "btn_refresh_hotkeys": "⟳  Siyahını yenilə",
        "section_translate_langs": "TƏRCÜMƏ DİLLƏRİ",
        "lang_note": "Popup-da siyahı kimi görünəcək dillər (ən çox 6 dil):",
        "section_ui_lang": "İNTERFEYS DİLİ",
        "label_ui_lang": "İnterfeys dili:",
        "dialog_error": "Xəta",
        "dialog_hotkey_empty": "Qısayol boş ola bilməz",
        "dialog_invalid_format": "Yanlış format",
        "dialog_warning": "Xəbərdarlıq",
        "dialog_max_langs": "Ən çox 6 dil seçə bilərsiniz",
        "dialog_saved": "Yadda saxlandı",
        "dialog_saved_msg": "✓ Bütün ayarlar yadda saxlandı!",
        "dialog_no_key_title": "API Açarı yoxdur",
        "dialog_no_key_msg": "Əvvəlcə OpenRouter API açarını daxil edin",
        "or_fetching": "⏳ Yüklənir…",
        "or_loaded": "✓ {count} model",
        "or_fetch_error_title": "Yükləmə xətası",
        "or_fetch_error_msg": "OpenRouter modelləri yüklənə bilmədi:\n{error}",
    },
    "Turkish": {
        "title": "◈  LUMTEXT",
        "section_selected": "SEÇİLEN METİN",
        "section_action": "İŞLEM",
        "no_text_warning": "⚠ Metin seçilmedi — önce metni seçin",
        "action_format": "Cümleyi düzelt & sadeleştir",
        "action_translate": "Çevir",
        "action_email": "E-posta için uyarla",
        "action_summarize": "Özetle",
        "action_tone_formal": "Resmi üsluba dönüştür",
        "action_tone_casual": "Gündelik üsluba dönüştür",
        "action_bulletpoints": "Madde işaretlerine çevir",
        "translate_lang_label": "Dil:",
        "result_placeholder": "Sonuç burada görünecek…",
        "status_api_missing": "⚠ API anahtarı bulunamadı — Ayarları kontrol edin",
        "status_processing": "AI yanıtlıyor…",
        "status_ready": "✓ Hazır",
        "status_error": "✗ Hata: {error}",
        "btn_run": "▶  Çalıştır",
        "btn_rerun": "▶  Yeniden çalıştır",
        "btn_cancel": "Kapat",
        "btn_copy_fmt": "⎘ Kopyala (biçimli)",
        "btn_copy_plain": "⎘ Düz kopyala",
        "btn_replace": "↩ Değiştir",
        "btn_actions": "☰ İşlemler",
        "btn_actions_hide": "▾ İşlemleri gizle",
        "btn_waiting": "⏳ Bekleyin…",
        "copy_success_fmt": "✓ Biçimli kopyalandı!",
        "copy_success_plain": "✓ Kopyalandı!",
        "replace_tooltip": "Seçilen metni sonuçla değiştirir",
        "fetch_tooltip": "OpenRouter modellerini yenile",
        "fetch_status_no_key": "⚠ OpenRouter API anahtarı yok — Ayarları kontrol edin",
        "fetch_status_error": "✗ Yükleme hatası: {error}",
        "provider_no_key": "{p}  (❌ anahtar yok)",
        "tray_tooltip": "Lumtext — Metin seç, Ctrl+Shift+Space bas",
        "tray_open_settings": "◈  Ayarları Aç",
        "tray_hotkey_info": "⌨  Metin seç → Ctrl+Shift+Space",
        "tray_quit": "✕  Çık",
        "startup_message": "Program çalışıyor!\n1. Metin seçin\n2. Ctrl+Shift+Space basın\n\n"
                          "Kısayol çalışmazsa: Ayarlar → Kısayol ayarlama kılavuzu",
        "tray_tooltip_fmt": "Lumtext\nKısayol: {hotkey}",
        "settings_title": "Lumtext — Ayarlar",
        "settings_subtitle": "AYARLAR · YAPILANDIRMA",
        "btn_save": "✓  Kaydet",
        "tab_model": "  ⚙  Model & API  ",
        "tab_hotkey": "  ⌨  Kısayollar  ",
        "tab_languages": "  🌐  Diller  ",
        "section_provider": "AI SAĞLAYICI",
        "label_provider": "Sağlayıcı:",
        "label_model": "Model:",
        "btn_fetch_models": "⟳ Modelleri yükle",
        "or_hint": "💡 openrouter.ai/models sayfasından herhangi bir model ID'sini yazabilirsiniz",
        "section_api_keys": "API ANAHTARLARI",
        "api_key_placeholder": "{p} API anahtarını girin…",
        "section_hotkey": "GENEL KISAYOL",
        "label_current_hotkey": "Mevcut kısayol:",
        "label_new_hotkey": "Yeni kısayol:",
        "hotkey_placeholder": "örn: <ctrl>+<shift>+a",
        "btn_set_hotkey": "Ayarla",
        "hotkey_format_hint": "Biçim: <ctrl>+<shift>+a  ·  <ctrl>+<alt>+t  ·  <super>+h",
        "section_system_hotkeys": "SİSTEMDE KULLANILAN KISAYOLLAR",
        "hotkey_note": "Aşağıdaki kısayollar sistemde kullanılıyor — bunları seçmeyin:",
        "btn_refresh_hotkeys": "⟳  Listeyi yenile",
        "section_translate_langs": "ÇEVİRİ DİLLERİ",
        "lang_note": "Popup'ta listelenecek diller (en fazla 6):",
        "section_ui_lang": "ARAYÜZ DİLİ",
        "label_ui_lang": "Arayüz dili:",
        "dialog_error": "Hata",
        "dialog_hotkey_empty": "Kısayol boş olamaz",
        "dialog_invalid_format": "Geçersiz biçim",
        "dialog_warning": "Uyarı",
        "dialog_max_langs": "En fazla 6 dil seçebilirsiniz",
        "dialog_saved": "Kaydedildi",
        "dialog_saved_msg": "✓ Tüm ayarlar kaydedildi!",
        "dialog_no_key_title": "API Anahtarı Yok",
        "dialog_no_key_msg": "Önce OpenRouter API anahtarını girin",
        "or_fetching": "⏳ Yükleniyor…",
        "or_loaded": "✓ {count} model",
        "or_fetch_error_title": "Yükleme hatası",
        "or_fetch_error_msg": "OpenRouter modelleri yüklenemedi:\n{error}",
    },
    "Russian": {
        "title": "◈  LUMTEXT",
        "section_selected": "ВЫБРАННЫЙ ТЕКСТ",
        "section_action": "ДЕЙСТВИЕ",
        "no_text_warning": "⚠ Текст не выбран — сначала выделите текст",
        "action_format": "Исправить и упростить",
        "action_translate": "Перевести",
        "action_email": "Адаптировать для письма",
        "action_summarize": "Резюмировать",
        "action_tone_formal": "Перевести в официальный стиль",
        "action_tone_casual": "Перевести в повседневный стиль",
        "action_bulletpoints": "Преобразовать в маркированный список",
        "translate_lang_label": "Язык:",
        "result_placeholder": "Результат появится здесь…",
        "status_api_missing": "⚠ API ключ не найден — Проверьте настройки",
        "status_processing": "AI отвечает…",
        "status_ready": "✓ Готово",
        "status_error": "✗ Ошибка: {error}",
        "btn_run": "▶  Выполнить",
        "btn_rerun": "▶  Выполнить снова",
        "btn_cancel": "Закрыть",
        "btn_copy_fmt": "⎘ Копировать (формат.)",
        "btn_copy_plain": "⎘ Копировать текст",
        "btn_replace": "↩ Заменить",
        "btn_actions": "☰ Действия",
        "btn_actions_hide": "▾ Скрыть действия",
        "btn_waiting": "⏳ Подождите…",
        "copy_success_fmt": "✓ Форматировано скопировано!",
        "copy_success_plain": "✓ Скопировано!",
        "replace_tooltip": "Заменить выделенный текст результатом",
        "fetch_tooltip": "Обновить модели OpenRouter",
        "fetch_status_no_key": "⚠ Отсутствует API ключ OpenRouter — Проверьте настройки",
        "fetch_status_error": "✗ Ошибка загрузки: {error}",
        "provider_no_key": "{p}  (❌ нет ключа)",
        "tray_tooltip": "Lumtext — Выделите текст, нажмите Ctrl+Shift+Space",
        "tray_open_settings": "◈  Открыть настройки",
        "tray_hotkey_info": "⌨  Выделите текст → Ctrl+Shift+Space",
        "tray_quit": "✕  Выход",
        "startup_message": "Программа запущена!\n1. Выделите текст\n2. Нажмите Ctrl+Shift+Space\n\n"
                          "Если горячая клавиша не работает: Настройки → Инструкция",
        "tray_tooltip_fmt": "Lumtext\nГорячая клавиша: {hotkey}",
        "settings_title": "Lumtext — Настройки",
        "settings_subtitle": "НАСТРОЙКИ · КОНФИГУРАЦИЯ",
        "btn_save": "✓  Сохранить",
        "tab_model": "  ⚙  Модель & API  ",
        "tab_hotkey": "  ⌨  Горячие клавиши  ",
        "tab_languages": "  🌐  Языки  ",
        "section_provider": "AI ПРОВАЙДЕР",
        "label_provider": "Провайдер:",
        "label_model": "Модель:",
        "btn_fetch_models": "⟳ Загрузить модели",
        "or_hint": "💡 Вы можете ввести ID любой модели с openrouter.ai/models",
        "section_api_keys": "API КЛЮЧИ",
        "api_key_placeholder": "Введите API ключ {p}…",
        "section_hotkey": "ГЛОБАЛЬНАЯ КЛАВИША",
        "label_current_hotkey": "Текущая клавиша:",
        "label_new_hotkey": "Новая клавиша:",
        "hotkey_placeholder": "напр: <ctrl>+<shift>+a",
        "btn_set_hotkey": "Установить",
        "hotkey_format_hint": "Формат: <ctrl>+<shift>+a  ·  <ctrl>+<alt>+t  ·  <super>+h",
        "section_system_hotkeys": "ЗАНЯТЫЕ СИСТЕМНЫЕ КЛАВИШИ",
        "hotkey_note": "Следующие клавиши уже используются — избегайте их:",
        "btn_refresh_hotkeys": "⟳  Обновить список",
        "section_translate_langs": "ЯЗЫКИ ПЕРЕВОДА",
        "lang_note": "Языки, отображаемые в списке (макс. 6):",
        "section_ui_lang": "ЯЗЫК ИНТЕРФЕЙСА",
        "label_ui_lang": "Язык интерфейса:",
        "dialog_error": "Ошибка",
        "dialog_hotkey_empty": "Горячая клавиша не может быть пустой",
        "dialog_invalid_format": "Неверный формат",
        "dialog_warning": "Предупреждение",
        "dialog_max_langs": "Вы можете выбрать не более 6 языков",
        "dialog_saved": "Сохранено",
        "dialog_saved_msg": "✓ Все настройки сохранены!",
        "dialog_no_key_title": "Нет API ключа",
        "dialog_no_key_msg": "Сначала введите API ключ OpenRouter",
        "or_fetching": "⏳ Загрузка…",
        "or_loaded": "✓ {count} моделей",
        "or_fetch_error_title": "Ошибка загрузки",
        "or_fetch_error_msg": "Не удалось загрузить модели OpenRouter:\n{error}",
    },
}


def set_language(lang: str):
    global _lang
    if lang in _L:
        _lang = lang


def get_language() -> str:
    return _lang


def tr(key: str, **kwargs) -> str:
    val = _L.get(_lang, {}).get(key) or _L.get("English", {}).get(key) or key
    if kwargs:
        return val.format(**kwargs)
    return val
